In [4]:
# TensorFlow로 간단한 계산하기
import tensorflow as tf

a = tf.constant(1234)
b = tf.constant(5000)

add_op = a + b

# 세션 시작하기
session = tf.Session()
res = session.run(add_op)
print(res)

AttributeError: module 'tensorflow' has no attribute 'Session'

In [3]:
# Tensorflow 2
import tensorflow as tf

a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(4)

# 연산 정의
calc1_op = a + b * c
calc2_op = (a + b) * c

# 세션 시작
session = tf.Session()
res1 = session.run(calc1_op)
print(res1)
res2 = session.run(calc2_op)
print(res2)

AttributeError: module 'tensorflow' has no attribute 'Session'

In [ ]:
# tensorflow 3
import tensorflow as tf

# 상수 정의
a = tf.constant(120, name="a")
b = tf.constant(130, name="b")
c = tf.constant(140, name="c")
# 변수 정의
v = tf.Variable(0, name="v")

# 데이터 플로우 그래프 정의
calc_op = a + b + c
assign_op = tf.assign(v, calc_op)

# 세션 실행
sess = tf.Session()
sess.run(assign_op)

# v 내용 출력
print(sess.run(v))

In [6]:
# TensorFlow Placeholder
import tensorflow as tf

# 플레이스홀더 정의
a = tf.placeholder(tf.int32, [3])

# 배열의 모든 값을 2배화하는 연산 정의
b = tf.constant(2)
x2_op = a * b

# 세션 시작
sess = tf.Session()

# 플레이스홀더에 값 넣고 실행
r1 = sess.run(x2_op, feed_dict={ a: [1, 2, 3]})
print(r1)
r2 = sess.run(x2_op, feed_dict={ a: [10, 20, 30] })
print(r2)

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [ ]:
# TensorFlow Placeholder 2
import tensorflow as tf

# 플레이스홀더 정의
a = tf.placeholder(tf.int32, [None]) # 배열의 크기를 None으로 지정

# 배열의 모든 값을 10배하는 연산 정의
b = tf.constant(10)
x10_op = a * b

# 세션 시작
sess = tf.Session()

# 플레이스홀더에 값을 넣어 실행
r1 = sess.run(x10_op, feed_dict={a: [1,2,3,4,5]})
print(r1)
r2 = sess.run(x10_op, feed_dict={a: [10,20]})
print(r2)

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

csv = pd.read_csv("bmi.csv")
csv["height"] = csv["height"] / 200
csv["weight"] = csv["weight"] / 100

bclass = {"thin": [1,0,0], "normal": [0,1,0], "fat": [0,0,1]}
csv["label_pat"] = csv["label"].apply(lambda x: np.array(bclass[x]))

# 테스트를 위한 데이터 분류
test_csv = csv[15000:20000]
test_pat = test_csv[["weight", "height"]]
test_ans = list(test_csv["label_pat"])

# 데이터 플로우 그래프 구축하기
# 플레이스홀더 선언하기
x = tf.placeholder(tf.float32, [None, 2])
y_ = tf.placeholder(tf.float32, [None, 3])

# 변수 선언
W = tf.Variable(tf.zeros([2,3]))
b = tf.Variable(tf.zeros([3]))

# 소프트맥스 회귀 정의
y = tf.nn.softmax(tf.matmul(x, W) + b)

# 모델 훈련
cross_entropy = -tf.reduce_sum(y_ * tf.log(y))
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(cross_entropy)

# 정답률 구하기
predict = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))
accuracy = tf.reduce_mean(tf.cast(predict, tf.float32))

# 세션 시작
sess = tf.Session()
sess.run(tf.tf.global_variables_initializer())

# 학습 시키기
for step in range(3500):
    i = (step * 100 % 14000)
    rows = csv[1 + i : 1 + i + 100]
    x_pat = rows[["weight","height"]]
    y_ans = list(rows["label_pat"])
    fd = {x: x_pat, y_: y_ans}
    sess.run(train, feed_dict=fd)
    if step % 500 == 0:
        cre = sess.run(cross_entropy, feed_dict=fd)
        acc = sess.run(accuracy, feed_dict={x: test_pat, y_: test_ans})
        print("step=", step, "cre=", cre, "acc=", acc)

# 최종 정답률 구하기
acc = sess.run(accuracy, feed_dict={x: test_pat, y_: test__ans})
print("정답률=", acc)

FileNotFoundError: [Errno 2] No such file or directory: 'bmi.csv'

## TensorBoard 사용하기
---
- 데이터의 흐름을 시각화하는 도구

In [3]:
import tensorflow as tf

# 데이터플로우 그래프 구축
a = tf.constant(20, name="a")
b = tf.constant(30, name="b")
mul_op = a * b

# 세션 생성
x

AttributeError: module 'tensorflow' has no attribute 'Session'

In [9]:
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.callbacks import EarlyStopping
import pandas as pd, numpy as np

# BMI 데이터를 읽고 정규화하기
csv = pd.read_csv("bmi.csv")

# 몸무게와 키 데이터
csv["weight"] /= 100
csv["height"] /= 200
X = csv[["weight", "height"]].as_matrix() # DataFrame to ndarray

# 레이블
bclass = {"thin":[1,0,0], "normal":[0,1,0], "fat":[0,0,1]}
y = np.empty((2000,3))
for i, v in enumerate(csv["label"]):
    y[i] = bclass[v]
    
# 훈련 전용 데이터와 테스트 전용 데이터로 나누기
X_train, y_train = X[1:15001], y[1:15001]
X_test, y_test = X[15001:20001], y[15001:20001]

# 모델 구조 정의하기
model = Sequential()
model.add(Dense(512, input_shape=(2,)))
model.add(Activation('relu'))
model.add(Dropout(0.1))

model.addd(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.1))

model.add(Dense(3))
model.add(Activation('softmax'))

# 모델 구축하기
model.compile(
    loss = 'categorical_crossentory',
    optimizer = "rmsprop",
    metrics = ['accuracy']
)

# 데이터 훈련
hist = model.fit(
    X_train, y_train,
    batch_size = 100,
    nb_epoch=20,
    validation_split=0.1,
    callbacks=[EarlyStopping(monitor='val_loss', patience=2)],
    verbose=1
)

# 테스트 데이터로 평가하기
score = model.evaluate(X_test, y_test)
print('loss=', score[0])
print('accuracy=', score[1])

FileNotFoundError: [Errno 2] No such file or directory: 'bmi.csv'

In [11]:
import pandas as pd
import numpy as np

test_data = pd.DataFrame({
    "column1": [1, 2, 3],
    "height": [1, 2, 3]
})
test_data

column1  height
0        1       1
1        2       2
2        3       3

In [14]:
test_data.values

array([[1, 1],
       [2, 2],
       [3, 3]])

## 이미지 관련 딥러닝
---
- Average Hash

In [3]:
from PIL import Image
import numpy as np

# 이미지 데이터를 Average Hash로 변환
def average_hash(fname, size=16):
    img = Image.open(fname)
    img = img.convert('L') # 그레이 스케일로 변환
    img = img.resize((size, size), Image.ANTIALIAS) # 리사이징
    pixel_data = img.getdata() # 픽셀데이터 가져오기
    pixels = np.array(pixel_data) # Numpy 배열로 변환하기
    pixels = pixels.reshape((size, size)) # 2차원 배열로 변환
    avg = pixels.mean() 
    diff = 1 * (pixels > avg) # 평균보다 크면 1, 작으면 0으로 변환하기
    return diff

# 이진 해시로 변환
def np2hash(ahash):
    bhash = []
    for nl in ahash.tolist():
        s1 = [str(i) for i in nl]
        s2 = "".join(s1)
        i = int(s2, 2) # 2진수를 정수로 변환
        bhash.append("%04x" % i)
    return "".join(bhash)

# Average Hash 출력하기
ahash = average_hash('yangws.jpg')
print(ahash)
print(np2hash(ahash))

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1]
 [1 1 1 1 1 0 0 0 0 0 0 0 1 1 1 1]
 [1 1 1 1 1 0 0 0 0 0 0 0 1 1 1 1]
 [1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 0 1 1 0 0 1 1 1 1]
 [1 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1]
 [1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1]
 [1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1]
 [1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1]
 [1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1]
 [1 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1]]
fffffc1ff80ff80ff81fffffff7ffefffccfe083c003c00fe01fe01fe03fe6ff


## 이미지 데이터를 파이썬 데이터로 변환하기
---

In [4]:
from PIL import Image
import os, glob
import numpy as np
from sklearn.model_selection import train_test_split

# 분류 대상 카테고리 선택
caltech_dir = "./image/101_ObjectCategories"
categories = ["chair", "camera", "butterfly", "elephant", "flamingo"]
nb_classes = len(categories)

# 이미지 크기 지정
image_w = 64
image_h = 64
pixels = image_w * image_h * 3 # RGB 값이니 3을 곱함

# 이미지 데이터 읽어들이기
X = []
Y = []
for idx, cat in enumerate(categories):
    label = [0 for i in range(nb_classes)]
    label[idx] = 1
    image_dir = caltech_dir + "/" + cat
    files = glob.glob(image_dir + "/*.jpg")
    # 각 이미지를 resize함
    for i, f in enumerate(files):
        img = Image.open(f)
        img = img.convert("RGB")
        img = img.resize((image_w, image_h))
        data = np.asarray(img)
        X.append(data)
        Y.append(label)
        if i % 10 == 0:
            print(i, "\n", data)

X = np.array(X)
Y = np.array(Y)

# 학습 전용 데이터와 테스트 전용 데이터 구분
X_train, X_test, y_train, y_test = \
    train_test_split(X, Y)
xy = (X_train, X_test, y_train, y_test)
np.save("./image/5obj.npy", xy)
print("OK", len(Y))

0 
 [[[ 40  24  31]
  [ 33  20  24]
  [ 27  16  20]
  ...
  [ 77  69  93]
  [ 75  66  92]
  [ 70  61  89]]

 [[ 40  25  32]
  [ 34  20  24]
  [ 31  19  23]
  ...
  [ 80  72  96]
  [ 77  68  94]
  [ 75  65  94]]

 [[ 41  26  33]
  [ 35  21  25]
  [ 33  22  26]
  ...
  [ 84  77 100]
  [ 82  74 100]
  [ 78  69  97]]

 ...

 [[189 162 192]
  [189 169 198]
  [175 160 191]
  ...
  [204 173 206]
  [202 170 204]
  [196 164 198]]

 [[154 131 164]
  [141 121 153]
  [137 119 150]
  ...
  [200 170 204]
  [195 165 200]
  [191 161 195]]

 [[129 111 145]
  [165 143 178]
  [184 157 195]
  ...
  [198 168 202]
  [199 169 203]
  [196 166 200]]]
10 
 [[[7 7 7]
  [4 4 4]
  [3 3 3]
  ...
  [4 4 4]
  [4 4 4]
  [8 8 8]]

 [[4 4 4]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [1 1 1]
  [4 4 4]]

 [[4 4 4]
  [1 1 1]
  [0 0 0]
  ...
  [0 0 0]
  [2 2 2]
  [3 3 3]]

 ...

 [[4 4 4]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [2 2 2]
  [3 3 3]]

 [[4 4 4]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [2 2 2]
  [3 3 3]]

 [[7 7 7]
  [4 

/Users/yang-wonseog/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)


## CNN으로 분류하기
---

In [3]:

from keras.models import Sequential
from keras.layers import Convolution2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
import numpy as np

# 카테고리 지정
categories = ["chair", "camera", "butterfly", "elephant", "flasmingo"]
nb_classes = len(categories)

# 이미지 사이즈 지정
image_w = 64
image_h = 64

# 데이터 불러오기
X_train, X_test, y_train, y_test = np.load("./image/5obj.npy", allow_pickle=True)

# 데이터 정규화 
X_train = X_train.astype("float") / 256
X_test = X_test.astype("float") / 256
print("X_train shape:", X_train.shape)

# 머신러닝을 하기 위한 keras모델 사용
model = Sequential
model.add(Convolution2D(32, 3, 3, border_mode='same',
                        input_shape=X_train.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(poo_size=(2,2)))
model.add(Dropout(0.25))

model.add(Convolution2D(64, 3, 3, border_mode='same'))
model.add(Activation('relu'))
model.add(Convolution2D(64, 3, 3))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(nb_classes))
model.add(Activation('softmax'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metris=['accuracy'])

# 모델 훈련하기
model.fit(X_train, y_train, batch_size=32, nb_epoch=50)

# 모델 평가하기
score = model.evaluate(X_test, y_test)
print('loss=', score[0])
print('accuracy=', score[1])

X_train shape: (250, 64, 64, 3)


TypeError: ('Keyword argument not understood:', 'border_mode')

## 이미지 분류
---
1. 데이터 검사 및 이해하기
2. 입력 파이프라인 빌드하기
3. 모델 빌드하기
4. 모델 훈련하기
5. 모델 테스트하기
6. 모델을 개선하고 프로세스 반복

In [4]:
import matplotlib.pyplot as plt
import numpy as np
import os
import 